### PR TITLE
Overhaul command matching

### PR DESCRIPTION
**Pull request by niyrme**
- fix `command_name` containing the `!`
  - fixed by moving the `^!` pattern before the `command_name` group
- remove useless pre-defined variables `command_name`, `command_input` and `command_match`
  - definition and instantiation of variables was not yet needed at that point
- add project directory (`.idea`) added by JetBrains IDEs (PyCharm, IntelliJ, etc.) to `.gitignore`

### CODE REVIEW

**Comment by niyrme** [comment]
Yea. This need manual resolving..

**Comment by niyrme** [comment]
pre-commit.ci autofix

**Comment by niyrme** [comment]
Perfect. Ready for merge..

**Review by bastienboutonnet — APPROVED** [review]
@niyrme this looks fantastic! thanks a lot for your help with this. Makes the code so much cleaner. I'll get it merged on the next stream. Not sure when that will be. Might try to squeeze one in tonight. I'm cancelling my Saturday stream as the weather is going to be really good and I need to interact with some people in real life. But ASAP!

**Pull request merged**
