### PR TITLE
Add __main__.py as main executable and python version check

### PR DESCRIPTION
**Pull request by dataCobra**
The advantage of `__main__.py` is its clear designation as the main executable in the directory structure and also Python understands it.

I've also added a version check to make sure the correct Python version is used before even starting the chatbot.

### CODE REVIEW

**Comment by bastienboutonnet** [comment]
Hey @dataCobra Thanks for the contribution! Also sorry for the delay this week was very busy! 

I wasn't really aware of this pattern actually but I'm not against it at all!

That being said, I think the bot is compatible with versions as far back as 3.7. We might want to relax this until I `pyupgrade` it to 3.9.

What do you think?

**Comment by dataCobra** [comment]
Hey @bastienboutonnet, no worries about the delay. :+1:

It's your repository and the decision sounds good and understandable. :slightly_smiling_face: 

Please also consider to rename the folder from `src/` to `chatbot/`. This will make the use of `__main__.py` even better, because then a straightforward `python chatbot` will find the `__main__.py` in the folder and does the rest.

**Comment by bastienboutonnet** [comment]
@dataCobra I agree with your last advise too.

Do you feel like updating the code so that the version check is more permissive?

If you feel like it I would say go ahead and rename the `src` folder to `chatbot` that's very nice! I might squeeze in a short stream in an hour or less so maybe I can do it on stream but I don't want to steal your thunder :)

**Comment by dataCobra** [comment]
> Do you feel like updating the code so that the version check is more permissive?

Sure, I can take care of it no problem. How permissive would you like version control to be?

> If you feel like it I would say go ahead and rename the `src` folder to `chatbot` that's very nice! I might squeeze in a short stream in an hour or less so maybe I can do it on stream but I don't want to steal your thunder :)

How do you prefer it? Even if it is only a name change of the directory, the explanation could be interesting for others in the livestream. :+1:

**Comment by bastienboutonnet** [comment]
> How permissive would you like the version check to be?

Let's allow 3.7 and up inclusive

> How do you prefer it? Even if it is only a name change of the directory, the explanation could be interesting for others in the livestream. 👍

True ok, then I can commit to your PR later on during stream. I can also take care of the version stuff too :) 

Maybe catch you later :)

**Comment by bastienboutonnet** [comment]
@dataCobra thanks for the changes related to the version. 

I'll do the dir change on stream as I think indeed it's potentially a nice learning!

**Pull request merged**
